import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :malipo, MalipoWeb.Endpoint, cache_static_manifest: "priv/static/cache_manifest.json"

# No `force_ssl`: Cloudflare enforces HTTPS at the edge and reaches the origin
# over plain HTTP, so an origin redirect loops forever. `MalipoWeb.Plugs.ForwardedScheme`
# restores the visitor's scheme from `cf-visitor` instead.

# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
